source 'https://github.com/MaieLee/MySpec.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'MLCamera_Example' do
  pod 'MLCamera', :path => '../'

  target 'MLCamera_Tests' do
    inherit! :search_paths

    
  end
end
